### ISSUE TITLE
npm, package.json

### ISSUE THREAD

**Issue by joshhartigan** [hedgehog1029/mediocre#1]
https://docs.npmjs.com/
  please start using npm properly!!!11one!
  it is super easy, kind to other people, and will make your life significantly happier.

**Comment by hedgehog1029** [comment]
111111!
Yeah, but this software is in so much of an alpha that I'm changing the required things almost every time I change the code, and I want to get this in at least a usable state (code errors out at the moment) before I make a package.json. I will.

**Comment by joshhartigan** [comment]
rtfm. https://docs.npmjs.com/

you don't need to have a 'finished' program to use a package.json, that's the whole point.

please actually read the docs, https://docs.npmjs.com/ https://docs.npmjs.com/ https://docs.npmjs.com/

**Comment by joshhartigan** [comment]
_you're not reading the docs._ npm will **change your package.json for
you** as you make changes. At least read the docs.

**Comment by hedgehog1029** [comment]
Fixed in 8adb9b1fad56168d15ad9c91364f999d14e1304f
